### ISSUE TITLE
PAR101 (only operators and comments are allowed)

### ISSUE THREAD

**Issue by cyyc1** [robsdedude/flake8-picky-parentheses#29]
Hi, thanks for writing this plugin!  I really like how PAR101 can check unaligned closing parenthesis.

However, I found that this plugin complains about the following code:

```python
def func123(*arg):
    print('hello world')
    return 1


ans1 = func123(
    1, 2, 3, 4, 5
) + 100  # this is Line 8

aa = [1, 2, 3, 4, 5, 6]

ans2 = aa[
    func123(1, 2, 3, 4, 5, 6, 7, 8, 9)
] + aa[0]  # this is Line 14
```

The message is:
```
test.py:8:1: PAR101: Only operators and comments are allowed after a closing bracket on a new line
test.py:14:1: PAR101: Only operators and comments are allowed after a closing bracket on a new line
```

I often need to write in such style (Line 8 and Line 14).  Can you give this violation a different code so that I can ignore this check?

Thank you!

**Comment by robsdedude** [comment]
Hi thanks for raising this. While I personally don't like this style I can totally see how others are fine with it. Moving this specific case to a new code seems like a reasonable solution allowing you do mute just this lint :+1: 

I'll see when I have time to tackle this.

**Comment by cyyc1** [comment]
Thanks!

It doesn't seem like a complicated fix, so I submitted a PR here: https://github.com/robsdedude/flake8-picky-parentheses/pull/30

Please feel free to review it and take over it when necessary.
