### ISSUE TITLE
Version 0.5.1 causes `pip check` error with current flake8

### ISSUE THREAD

**Issue by OnBeyondBeing** [robsdedude/flake8-picky-parentheses#35]
To reproduce, run:
> pip install flake8-picky-parentheses
> pip install -U flake8
> pip check

Returns:
> flake8-picky-parentheses 0.5.1 has requirement flake8~=3.7, but you have flake8 6.1.0.

I think that: 
https://github.com/robsdedude/flake8-picky-parentheses/blob/b35bb66f9737727b18595012b25e30f14ca14503/pyproject.toml#L10

should actually be:

>"flake8>=3.7",

**Comment by robsdedude** [comment]
Whoops. Sorry for the inconvenience. 0.5.2 is out and should fix this. Thanks for the report.
